name: build

on:
  push:
  pull_request:

jobs:
  linux:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: make
